image: docker:24.0.4-git

options:
  docker: true

pipelines:
  default:
    - step:
        name: Deploy
        image: python:3.9-alpine
        caches:
          - pip
        script:
          - export GIT_BRANCH=$BITBUCKET_BRANCH
          - export GIT_REPO=https://$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD@bitbucket.org/$BITBUCKET_REPO_FULL_NAME
          - apk update && apk add --no-cache openssh-client sshpass git
          - pip install --no-cache-dir ansible
          - mkdir -p ~/.ssh
          - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/private_key
          - chmod -R 600 ~/.ssh/
          - git clone --depth=1 https://gitlab.com/babidi34/ansible-pipeline.git
          - cd ansible-pipeline
          - ansible-galaxy install -r requirements.yml
          - echo "[all]" > inventory
          - echo $SSH_HOSTS >> inventory
          - echo "$SSH_HOSTS ansible_ssh_user=$SSH_USER ansible_ssh_private_key_file=~/.ssh/private_key ansible_ssh_port=$SSH_PORT" >> inventory
          - ansible-playbook -i inventory update-webapp.yml --ssh-extra-args='-o StrictHostKeyChecking=no'
definitions:
  caches:
    pip: /root/.cache/pip
