image: docker:24.0.4-git

options:
  docker: true

pipelines:
  default:
    - step:
        name: Deploy
        image: python:3.9-alpine
        caches:
          - pip
        script:
          - apk update && apk add --no-cache openssh-client sshpass git
          - pip install --no-cache-dir ansible
          - mkdir -p ~/.ssh
          - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          - echo "$SSH_CONFIG" > ~/.ssh/config
          - chmod 600 ~/.ssh/id_rsa
          - ssh-keyscan $SSH_HOSTS >> ~/.ssh/known_hosts
          - git clone --depth=1 https://gitlab.com/babidi34/ansible-pipeline.git
          - cd ansible-pipeline
          - ansible-galaxy install -r requirements.yml
          - echo "[all]" > inventory
          - echo $SSH_HOSTS >> inventory
          - ansible-playbook -i inventory update-webapp.yml

definitions:
  caches:
    pip: /root/.cache/pip

variables:
  ANSIBLE_SSH_COMMON_ARGS: "-F ~/.ssh/config"
  ANSIBLE_HOST_KEY_CHECKING: False
  GIT_REPO: $BITBUCKET_GIT_HTTP_ORIGIN
  GIT_BRANCH: "master"
  COMMAND_ENDING: "composer install --no-interaction --no-scripts && npm install && npm run build && php artisan migrate"